#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 54.210.52.84:80 check\n\tserver server2 34.203.38.250:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
